//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual updates are kept in sync with AppResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiMovies.UI.Resources.Strings
{
	using System;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class AppResources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal AppResources() { }

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiMovies.UI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		// Home
		public static string Welcome_Title => ResourceManager.GetString("Welcome_Title", resourceCulture);
		public static string Welcome_Subtitle => ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
		public static string Section_Trending => ResourceManager.GetString("Section_Trending", resourceCulture);
		public static string Trending_Empty => ResourceManager.GetString("Trending_Empty", resourceCulture);

		// PreLogin
		public static string PreLogin_Title => ResourceManager.GetString("PreLogin_Title", resourceCulture);
		public static string PreLogin_Benefit_Rate => ResourceManager.GetString("PreLogin_Benefit_Rate", resourceCulture);
		public static string PreLogin_Benefit_Lists => ResourceManager.GetString("PreLogin_Benefit_Lists", resourceCulture);
		public static string PreLogin_Benefit_Personal => ResourceManager.GetString("PreLogin_Benefit_Personal", resourceCulture);
		public static string PreLogin_Benefit_Recommendations => ResourceManager.GetString("PreLogin_Benefit_Recommendations", resourceCulture);
		public static string PreLogin_Login_Button => ResourceManager.GetString("PreLogin_Login_Button", resourceCulture);
		public static string PreLogin_Footer => ResourceManager.GetString("PreLogin_Footer", resourceCulture);

		// Login
		public static string Login_Title => ResourceManager.GetString("Login_Title", resourceCulture);
		public static string Login_Username => ResourceManager.GetString("Login_Username", resourceCulture);
		public static string Login_Password => ResourceManager.GetString("Login_Password", resourceCulture);
		public static string Login_SignIn_Button => ResourceManager.GetString("Login_SignIn_Button", resourceCulture);
		public static string Login_InvalidCredentials => ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);

		// Profile
		public static string Profile_Hello => ResourceManager.GetString("Profile_Hello", resourceCulture);
		public static string Profile_Guest => ResourceManager.GetString("Profile_Guest", resourceCulture);
		public static string Profile_Lists => ResourceManager.GetString("Profile_Lists", resourceCulture);
		public static string Profile_Favorites => ResourceManager.GetString("Profile_Favorites", resourceCulture);
		public static string Profile_Watchlist => ResourceManager.GetString("Profile_Watchlist", resourceCulture);
		public static string Profile_Ratings => ResourceManager.GetString("Profile_Ratings", resourceCulture);

		// Details
		public static string MovieDetails_Title => ResourceManager.GetString("MovieDetails_Title", resourceCulture);
		public static string TvDetails_Title => ResourceManager.GetString("TvDetails_Title", resourceCulture);
		public static string PersonDetails_Title => ResourceManager.GetString("PersonDetails_Title", resourceCulture);
		public static string Common_ComingSoon => ResourceManager.GetString("Common_ComingSoon", resourceCulture);
	}
}
